version: 2
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . myenv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "myenv"
      - run:
          name: Running tests
          command: |
            . myenv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-66-248-136.ap-south-1.compute.amazonaws.com mkdir /home/ubuntu/test2222 \ 
            pwd && ls  
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
