version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . myenv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "myenv"
      - run:
          name: Running tests
          command: |
            . myenv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -i key/$ ubuntu@52.66.248.136 
            cd heroku_project
            git fetch
            git pull
